name: deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.DEPLOYKEY }}
    - name: push master
      env:
        API_URL: ${{ secrets.API_URL }}
        GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        FRONTEND_ROOT: ${{ secrets.FRONTEND_ROOT }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        SIGNINGKEY: ${{ secrets.SIGNINGKEY }}
      run: |-
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_EMAIL"
        git config --global gpg.format ssh
        git config --global commit.gpgsign true
        echo $SIGNINGKEY > signingkey
        git config --global user.signingkey $PWD/signingkey
        sh deploy.sh

'on':
  push:
    branches:
    - '*'
